// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateDeckInput struct {
	OwnerID string `json:"ownerId"`
	Name    string `json:"name"`
}

type Deck struct {
	ID        string `json:"id"`
	OwnerID   string `json:"ownerId"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"createdAt"`
}
