// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (
    id,
    owner_id,
    name,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_id, name, created_at
`

type CreateDeckParams struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, owner_id, name, created_at
FROM decks
WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listDecksByOwner = `-- name: ListDecksByOwner :many
SELECT id, owner_id, name, created_at
FROM decks
WHERE owner_id = $1
ORDER BY created_at
`

func (q *Queries) ListDecksByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
