// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deck struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	CreatedAt    pgtype.Timestamptz
	PasswordHash string
}
