package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/JosePintos/tora/apps/api/internal/deck/application/commands"
	"github.com/JosePintos/tora/apps/api/internal/interfaces/graphql/mapper"
	"github.com/JosePintos/tora/apps/api/internal/interfaces/graphql/model"
	"github.com/google/uuid"
)

// CreateDeck is the resolver for the createDeck field.
func (r *mutationResolver) CreateDeck(ctx context.Context, input *model.CreateDeckInput) (*model.Deck, error) {
	ownerID, err := uuid.Parse(input.OwnerID)
	if err != nil {
		return nil, fmt.Errorf("invalid ownerID: %w", err)
	}

	cmd := commands.CreateDeckCommand{
		Name:    input.Name,
		OwnerID: ownerID,
	}

	deck, err := r.Container.DeckService.Create(ctx, cmd)
	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLDeck(deck), nil
}

// Decks is the resolver for the decks field.
func (r *queryResolver) Decks(ctx context.Context, ownerID string) ([]*model.Deck, error) {
	parsedOwnerID, err := uuid.Parse(ownerID)
	if err != nil {
		return nil, fmt.Errorf("invalid ownerID: %w", err)
	}

	decks, err := r.Container.DeckService.ListByOwner(ctx, parsedOwnerID)
	if err != nil {
		return nil, err
	}

	graphqlDecks := make([]*model.Deck, 0, len(decks))
	for _, deck := range decks {
		graphqlDecks = append(graphqlDecks, mapper.ToGraphQLDeck(deck))
	}

	return graphqlDecks, nil
}
