package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/JosePintos/tora/apps/api/internal/interfaces/graphql/generated"
	"github.com/JosePintos/tora/apps/api/internal/interfaces/graphql/mapper"
	"github.com/JosePintos/tora/apps/api/internal/interfaces/graphql/model"
	"github.com/JosePintos/tora/apps/api/internal/user/application/commands"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input *model.RegisterInput) (*model.User, error) {
	cmd := commands.CreateUserCommand{
		Username: input.Username,
		Password: input.Password,
	}

	user, err := r.Container.UserService.Create(ctx, cmd)
	if err != nil {
		return nil, err
	}

	return mapper.ToGraphQLUser(user), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
